
const UPDATE_VIEW_STATE_BY_FETCHED_DATA = 'UPDATE_VIEW_STATE_BY_FETCHED_DATA';
const APPEND_PAGING_DATA_TO_VIEW_STATE = 'APPEND_PAGING_DATA_TO_VIEW_STATE';

export const SurveyList = {
    UPDATE_VIEW_STATE_BY_FETCHED_DATA   : 'SurveyList.'+UPDATE_VIEW_STATE_BY_FETCHED_DATA,
    APPEND_PAGING_DATA_TO_VIEW_STATE    : 'SurveyList.'+APPEND_PAGING_DATA_TO_VIEW_STATE
};

export const Survey = {
    UPDATE_VIEW_STATE_BY_FETCHED_DATA   : 'Survey.'+UPDATE_VIEW_STATE_BY_FETCHED_DATA,
    START_RESPOND                       : 'Survey.START_RESPOND',
    ADD_RESPONSE_ITEM                   : 'Survey.ADD_RESPONSE_ITEM',
    SUBMIT_RESPONSE_ITEMS               : 'Survey.SUBMIT_RESPONSE_ITEMS',
    SUBMIT_RESPONSE                     : 'Survey.SUBMIT_RESPONSE'
};

export const SurveyResponse = {
    UPDATE_VIEW_STATE_BY_FETCHED_DATA   : 'SurveyResponse.'+UPDATE_VIEW_STATE_BY_FETCHED_DATA
};


export const Profile = {
    UPDATE_VIEW_STATE_BY_FETCHED_DATA   : 'Profile.'+UPDATE_VIEW_STATE_BY_FETCHED_DATA
};

export const ResponseList = {
    UPDATE_VIEW_STATE_BY_FETCHED_DATA   : 'ResponseList.'+UPDATE_VIEW_STATE_BY_FETCHED_DATA,
    APPEND_PAGING_DATA_TO_VIEW_STATE    : 'ResponseList.'+APPEND_PAGING_DATA_TO_VIEW_STATE
};

export const ProfileResponse = {
    UPDATE_VIEW_STATE_BY_FETCHED_DATA   : 'ProfileResponse.'+UPDATE_VIEW_STATE_BY_FETCHED_DATA
};
