INSERT INTO `SURVEY` (`ID`, `USER_ID`, `SERVICE_ID`, `TITLE`, `DESCRIPTION`, `WELCOME_TEXT`, `END_TEXT`, `END_URL`, `END_URL_DESCRIPTION`, `TERMINATION_TEXT`, `ACTIVE`, `START_TIME`, `EXPIRY_TIME`, `QUESTION_COUNT`, `CREATE_TIME`, `UPDATE_TIME`) values('1','survey','malls','五洲精选调查问卷','您好！我们围绕生活所需，为您精选五大洲产品，会员专享有收益，会员专享每周更新，会员专享服务实在又贴心，调查问卷希望您能提供宝贵意见，请您如实回答，真心感谢您的支持和配合。','欢迎填写问卷！','问卷到此结束，感谢您的参与！','https://preferentialshop.591malls.com','进入我们的商城','问卷被终止',true,NOW(),'2100-01-01 00:00:00','10',NOW(),NOW());
INSERT INTO `SURVEY_SETTING` (`SURVEY_ID`, `RESPONSE_LIMIT`, `TEMPLATE`, `FORMAT`, `LOCALE`, `ACCESS_RULE`, `AUTO_REDIRECT`, `SHOW_GROUP_INFO`, `SHOW_PROGRESS`, `SHOW_QUESTION_INDEX`, `SHOW_RESPONSE`, `SHOW_WELCOME`, `ALLOW_EDIT_AFTER_COMPLETION`, `ALLOW_PREV`, `ALLOW_SUSPEND`, `ENABLE_ASSESSMENT`, `ENABLE_CAPTCHA`) values('1','1000000000',NULL,'ALL_IN_ONE','zh_CN','PUBLIC',true,true,true,true,true,true,true,true,true,true,false);


INSERT INTO `QUESTION` (`ID`, `SURVEY_ID`, `PARENT_ID`, `QUESTION_TYPE`, `QUESTION_CODE`, `INDEX`, `TITLE`, `IMAGE`, `HELP`, `CONTENT`, `MANDATORY`, `DEFAULT_ANSWER`, `JUMP_LOGIC`, `CREATE_TIME`, `UPDATE_TIME`) VALUES('1','1',NULL,'TEXT_INPUT','sid','1','请输入您的邀请码（没有邀请码可以忽略）',NULL,NULL,NULL,FALSE,NULL,NULL,NOW(),NOW());
INSERT INTO `QUESTION` (`ID`, `SURVEY_ID`, `PARENT_ID`, `QUESTION_TYPE`, `QUESTION_CODE`, `INDEX`, `TITLE`, `IMAGE`, `HELP`, `CONTENT`, `MANDATORY`, `DEFAULT_ANSWER`, `JUMP_LOGIC`, `CREATE_TIME`, `UPDATE_TIME`) VALUES('2','1',NULL,'RADIO','online_shopping','2','您经常在网上（淘宝、京东、1号店等）购物吗？',NULL,NULL,'{\"layout\":\"V\",\"options\":[{\"value\":\"true\",\"label\":\"是\"},{\"value\":\"false\",\"label\":\"否\"}]}',TRUE,NULL,NULL,NOW(),NOW());
INSERT INTO `QUESTION` (`ID`, `SURVEY_ID`, `PARENT_ID`, `QUESTION_TYPE`, `QUESTION_CODE`, `INDEX`, `TITLE`, `IMAGE`, `HELP`, `CONTENT`, `MANDATORY`, `DEFAULT_ANSWER`, `JUMP_LOGIC`, `CREATE_TIME`, `UPDATE_TIME`) VALUES('3','1',NULL,'RADIO','oversea_shopping','3','您了解海淘吗？ ',NULL,NULL,'{\"layout\":\"V\",\"options\":[{\"value\":\"true\",\"label\":\"是\"},{\"value\":\"false\",\"label\":\"否\"}]}',TRUE,NULL,NULL,NOW(),NOW());
INSERT INTO `QUESTION` (`ID`, `SURVEY_ID`, `PARENT_ID`, `QUESTION_TYPE`, `QUESTION_CODE`, `INDEX`, `TITLE`, `IMAGE`, `HELP`, `CONTENT`, `MANDATORY`, `DEFAULT_ANSWER`, `JUMP_LOGIC`, `CREATE_TIME`, `UPDATE_TIME`) VALUES('4','1',NULL,'RADIO','oversea_shopping_way','4','如果海淘，你会选择什么途径？',NULL,NULL,'{\"layout\":\"V\",\"options\":[{\"value\":\"friend purchasing\",\"label\":\"朋友代购\"},{\"value\":\"online purchasing\",\"label\":\"网上代购\"}, {\"value\":\"duty-free shop purchasing\",\"label\":\"免税店购买\"},{\"value\":\"other\",\"label\":\"其他\",\"ext\":true,\"extLabel\":\"其他途径\"}]}',TRUE,NULL,NULL,NOW(),NOW());
INSERT INTO `QUESTION` (`ID`, `SURVEY_ID`, `PARENT_ID`, `QUESTION_TYPE`, `QUESTION_CODE`, `INDEX`, `TITLE`, `IMAGE`, `HELP`, `CONTENT`, `MANDATORY`, `DEFAULT_ANSWER`, `JUMP_LOGIC`, `CREATE_TIME`, `UPDATE_TIME`) VALUES('5','1',NULL,'RADIO','care_for_products','5','海淘时您会关注什么样的商品？',NULL,NULL,'{\"layout\":\"V\",\"options\":[{\"value\":\"beauty products\",\"label\":\"美妆产品\"},{\"value\":\"maternal and child products\",\"label\":\"母婴产品\"}, {\"value\":\"home supplies\",\"label\":\"家居生活\"},{\"value\":\"health care products\",\"label\":\"保健产品\"}]}',TRUE,NULL,NULL,NOW(),NOW());
INSERT INTO `QUESTION` (`ID`, `SURVEY_ID`, `PARENT_ID`, `QUESTION_TYPE`, `QUESTION_CODE`, `INDEX`, `TITLE`, `IMAGE`, `HELP`, `CONTENT`, `MANDATORY`, `DEFAULT_ANSWER`, `JUMP_LOGIC`, `CREATE_TIME`, `UPDATE_TIME`) VALUES('6','1',NULL,'RADIO','consumption_level','6','您每月的网上消费是怎样一个水平？',NULL,NULL,'{\"layout\":\"V\",\"options\":[{\"value\":\"1000\",\"label\":\"1000\"},{\"value\":\"1000-3000\",\"label\":\"1000-3000\"}, {\"value\":\"3000-5000\",\"label\":\"3000-5000\"},{\"value\":\"5000\",\"label\":\"5000以上\"}]}',TRUE,NULL,NULL,NOW(),NOW());
INSERT INTO `QUESTION` (`ID`, `SURVEY_ID`, `PARENT_ID`, `QUESTION_TYPE`, `QUESTION_CODE`, `INDEX`, `TITLE`, `IMAGE`, `HELP`, `CONTENT`, `MANDATORY`, `DEFAULT_ANSWER`, `JUMP_LOGIC`, `CREATE_TIME`, `UPDATE_TIME`) VALUES('7','1',NULL,'RADIO','your_worries','7','您在网购中最担心的遇到什么样的问题？',NULL,NULL,'{\"layout\":\"V\",\"options\":[{\"value\":\"genuine\",\"label\":\"收到的实物与照片不符\"},{\"value\":\"quality\",\"label\":\"收到的产品质量差\"}, {\"value\":\"after-sales attitude\",\"label\":\"售后态度差\"},{\"value\":\"other\",\"label\":\"其他\"}]}',TRUE,NULL,NULL,NOW(),NOW());
INSERT INTO `QUESTION` (`ID`, `SURVEY_ID`, `PARENT_ID`, `QUESTION_TYPE`, `QUESTION_CODE`, `INDEX`, `TITLE`, `IMAGE`, `HELP`, `CONTENT`, `MANDATORY`, `DEFAULT_ANSWER`, `JUMP_LOGIC`, `CREATE_TIME`, `UPDATE_TIME`) VALUES('8','1',NULL,'RADIO','o2o','8','是否希望有一家线上线下相结合、服务优质的店在您身边？',NULL,NULL,'{\"layout\":\"V\",\"options\":[{\"value\":\"true\",\"label\":\"是\"},{\"value\":\"false\",\"label\":\"否\",\"ext\":true,\"extLabel\":\"原因\"}]}',TRUE,NULL,NULL,NOW(),NOW());
INSERT INTO `QUESTION` (`ID`, `SURVEY_ID`, `PARENT_ID`, `QUESTION_TYPE`, `QUESTION_CODE`, `INDEX`, `TITLE`, `IMAGE`, `HELP`, `CONTENT`, `MANDATORY`, `DEFAULT_ANSWER`, `JUMP_LOGIC`, `CREATE_TIME`, `UPDATE_TIME`) VALUES('9','1',NULL,'RADIO','to_store_experience','9','如果有，您是否愿意到店里体验？',NULL,NULL,'{\"layout\":\"V\",\"options\":[{\"value\":\"true\",\"label\":\"是\"},{\"value\":\"false\",\"label\":\"否\",\"ext\":true,\"extLabel\":\"原因\"}]}',TRUE,NULL,NULL,NOW(),NOW());
INSERT INTO `QUESTION` (`ID`, `SURVEY_ID`, `PARENT_ID`, `QUESTION_TYPE`, `QUESTION_CODE`, `INDEX`, `TITLE`, `IMAGE`, `HELP`, `CONTENT`, `MANDATORY`, `DEFAULT_ANSWER`, `JUMP_LOGIC`, `CREATE_TIME`, `UPDATE_TIME`) VALUES('10','1',NULL,'CELLPHONE_INPUT','phone_number','10','输入您的手机号，让我们可以联系到您吧？',NULL,NULL,NULL,TRUE,NULL,NULL,NOW(),NOW());
INSERT INTO `QUESTION` (`ID`, `SURVEY_ID`, `PARENT_ID`, `QUESTION_TYPE`, `QUESTION_CODE`, `INDEX`, `TITLE`, `IMAGE`, `HELP`, `CONTENT`, `MANDATORY`, `DEFAULT_ANSWER`, `JUMP_LOGIC`, `CREATE_TIME`, `UPDATE_TIME`) VALUES('11','1',NULL,'GEO','geo','11','为了给您提供更好的体验和服务，输入您的地址？（在手机上可以点击地图上的按钮 ⊙ 输入当前位置哦）',NULL,NULL,NULL,TRUE,NULL,NULL,NOW(),NOW());
